// Package swagger serves Swagger UI for OpenAPI 3 specs generated by go-swagger3.
//
// Mount the handler under /swagger/ and open http://localhost:8080/swagger/index.html:
//
//	spec, err := os.ReadFile("oas.json")
//	if err != nil {
//		log.Fatal(err)
//	}
//	http.Handle("/swagger/", swagger.Handler(spec))
//	log.Fatal(http.ListenAndServe(":8080", nil))
//
// Framework adapters live in separate modules under swagger/<name>/ (gin, echo, chi,
// mux, fiber, hertz, buffalo, flamingo, atreugo) so the main module stays lean.
package swagger

import (
	"html/template"
	"net/http"
	"os"
	"path"
	"regexp"
	"strings"
)

// Config holds Swagger UI options.
type Config struct {
	// URL is the document path relative to the UI (default "doc.json").
	URL string
	// Title is shown in the browser tab.
	Title string
	// Spec is the OpenAPI 3 document (JSON or YAML). Served at doc.json by default.
	Spec []byte
}

// Option configures the handler.
type Option func(*Config)

// URL sets the OpenAPI document path passed to Swagger UI (default "doc.json").
func URL(u string) Option {
	return func(c *Config) {
		c.URL = u
	}
}

// Title sets the HTML page title.
func Title(t string) Option {
	return func(c *Config) {
		c.Title = t
	}
}

// Handler returns an http.Handler that serves Swagger UI and the OpenAPI spec.
// Register it with a trailing slash:
//
//	http.Handle("/swagger/", swagger.Handler(spec))
func Handler(spec []byte, opts ...Option) http.Handler {
	cfg := &Config{
		URL:   "doc.json",
		Title: "Swagger UI",
		Spec:  spec,
	}
	for _, opt := range opts {
		opt(cfg)
	}
	return &uiHandler{
		cfg:   cfg,
		index: template.Must(template.New("index").Parse(indexHTML)),
	}
}

// HandlerFromFile loads an OpenAPI file and returns a Swagger UI handler.
func HandlerFromFile(filePath string, opts ...Option) (http.Handler, error) {
	spec, err := os.ReadFile(filePath)
	if err != nil {
		return nil, err
	}
	return Handler(spec, opts...), nil
}

// WrapHandler serves Swagger UI without an embedded spec. Point URL at a
// separately served OpenAPI document, or prefer Handler(spec).
var WrapHandler = Handler(nil)

type uiHandler struct {
	cfg   *Config
	index *template.Template
}

// Matches /prefix/ and optional remainder, ignoring query string.
var pathRE = regexp.MustCompile(`^(.*/)([^?]*?)(?:\?.*)?$`)

// normalizeRequestURI trims a trailing slash on file-like paths (e.g. index.html/).
// Some frameworks (notably Buffalo) append trailing slashes to all routes.
func normalizeRequestURI(raw string) string {
	pathPart, query, hasQuery := strings.Cut(raw, "?")
	if pathPart != "/" && strings.HasSuffix(pathPart, "/") {
		trimmed := strings.TrimSuffix(pathPart, "/")
		if strings.Contains(path.Base(trimmed), ".") {
			pathPart = trimmed
		}
	}
	if hasQuery {
		return pathPart + "?" + query
	}
	return pathPart
}

func (h *uiHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	matches := pathRE.FindStringSubmatch(normalizeRequestURI(r.URL.RequestURI()))
	if matches == nil {
		http.NotFound(w, r)
		return
	}
	prefix, name := matches[1], matches[2]

	switch name {
	case "", ".":
		http.Redirect(w, r, path.Join(prefix, "index.html"), http.StatusMovedPermanently)
	case "index.html":
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_ = h.index.Execute(w, h.cfg)
	default:
		if name == h.cfg.URL || isSpecName(name) {
			h.writeSpec(w, r, name)
			return
		}
		http.NotFound(w, r)
	}
}

func isSpecName(name string) bool {
	switch name {
	case "doc.json", "doc.yaml", "doc.yml", "oas.json", "oas.yml", "oas.yaml", "openapi.json", "openapi.yml", "openapi.yaml":
		return true
	default:
		return false
	}
}

func (h *uiHandler) writeSpec(w http.ResponseWriter, r *http.Request, name string) {
	if len(h.cfg.Spec) == 0 {
		http.NotFound(w, r)
		return
	}
	if strings.HasSuffix(name, ".yml") || strings.HasSuffix(name, ".yaml") {
		w.Header().Set("Content-Type", "application/yaml; charset=utf-8")
	} else {
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
	}
	_, _ = w.Write(h.cfg.Spec)
}

const indexHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{.Title}}</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css">
  <style>
    html { box-sizing: border-box; overflow-y: scroll; }
    *, *:before, *:after { box-sizing: inherit; }
    body { margin: 0; background: #fafafa; }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js" crossorigin></script>
  <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-standalone-preset.js" crossorigin></script>
  <script>
    window.onload = function () {
      window.ui = SwaggerUIBundle({
        url: "{{.URL}}",
        dom_id: "#swagger-ui",
        deepLinking: true,
        docExpansion: "list",
        presets: [SwaggerUIBundle.presets.apis, SwaggerUIStandalonePreset],
        plugins: [SwaggerUIBundle.plugins.DownloadUrl],
        layout: "StandaloneLayout",
        validatorUrl: null
      });
    };
  </script>
</body>
</html>
`
